apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: z4u2ako2n-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/z4u2ako2n-java-quarkus-gitops